# Generated by Django 4.0.8 on 2023-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Visit', 'Visit'), ('Camp', 'Camp'), ('Fest', 'Fest'), ('Cultural festival', 'Cultural Festival'), ('Party', 'Party')], max_length=50)),
                ('name_of_event', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('department', models.CharField(choices=[('SSET', 'Sharda School of Engineering and Technology'), ('SSAHS', 'Sharda School of Allied Health Sciences'), ('SSBSR', 'Sharda School of Basic Sciences and Research'), ('SSMFE', 'Sharda School of Media, Film and Entertainment')], max_length=50)),
                ('for_batch', models.CharField(choices=[('first year', 'First year (1st Year)'), ('second year', 'Second year (2nd Year)'), ('third year', 'Third year (3rd Year)'), ('fourth year', 'Fourth year (4th Year)'), ('fifth year', 'Fifth year (5th Year)')], max_length=50)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('organiser_name', models.CharField(max_length=200)),
                ('organiser_phone', models.CharField(max_length=200)),
                ('organiser_email', models.CharField(max_length=200)),
                ('last_date_to_register', models.DateField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_school', models.CharField(choices=[('SSET', 'Sharda School of Engineering and Technology'), ('SSAHS', 'Sharda School of Allied Health Sciences'), ('SSBSR', 'Sharda School of Basic Sciences and Research'), ('SSMFE', 'Sharda School of Media, Film and Entertainment')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='systemid',
            field=models.IntegerField(default=0),
        ),
    ]
