# Generated by Django 4.0.8 on 2023-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organiser',
            old_name='date',
            new_name='event_date',
        ),
        migrations.AlterField(
            model_name='organiser',
            name='department',
            field=models.CharField(choices=[('SSET', 'Sharda School of Engineering and Technology'), ('SSAHS', 'Sharda School of Allied Health Sciences'), ('SSBSR', 'Sharda School of Basic Sciences and Research'), ('SSMFE', 'Sharda School of Media, Film and Entertainment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='your_school',
            field=models.CharField(choices=[('SSET', 'Sharda School of Engineering and Technology'), ('SSAHS', 'Sharda School of Allied Health Sciences'), ('SSBSR', 'Sharda School of Basic Sciences and Research'), ('SSMFE', 'Sharda School of Media, Film and Entertainment')], max_length=50),
        ),
    ]
