# Generated by Django 4.0.8 on 2023-06-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_organiser_user_id_organiser_id_organiser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
