# Generated by Django 4.0.8 on 2023-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_organiser_thumbnail_alter_organiser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='organiser_email',
            field=models.EmailField(max_length=254),
        ),
    ]
