# Generated by Django 4.0.8 on 2023-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_organiser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
