# Generated by Django 4.0.8 on 2023-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_organiser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='user',
        ),
        migrations.AddField(
            model_name='organiser',
            name='user_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
