# Generated by Django 4.0.8 on 2023-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_organiser_organiser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
