# Generated by Django 4.0.8 on 2023-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_organiser_id_alter_organiser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='id',
        ),
        migrations.AlterField(
            model_name='organiser',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
