# Generated by Django 4.0.8 on 2023-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_organiser_id_alter_organiser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='organiser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organiser',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
