# Generated by Django 4.0.8 on 2023-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_category_id_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='organiser',
            name='event_type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Visit', 'Visit'), ('Camp', 'Camp'), ('Cultural festival', 'Cultural festival')], max_length=50),
        ),
    ]
