# Generated by Django 4.0.8 on 2023-07-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_department_alter_organiser_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='department',
            field=models.CharField(choices=[('Sharda School of Engineering and Technology', 'Sharda School of Engineering and Technology'), ('Sharda School of Allied Health Sciences', 'Sharda School of Allied Health Sciences'), ('Sharda School of Basic Sciences and Research', 'Sharda School of Basic Sciences and Research')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='event_type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Visit', 'Visit'), ('Camp', 'Camp'), ('Cultural festival', 'Cultural festival'), ('Party', 'Party')], max_length=50),
        ),
    ]
